### ISSUE TITLE
Can we add the feature to disable auto get request on connect back in?

### ISSUE THREAD

**Issue by rtrue983** [mongoose-os-libs/aws#13]
The change is as easy as setting `ss->want_get = false` here https://github.com/mongoose-os-libs/aws/blob/master/src/mgos_aws_shadow.c#L274 based on a flag sent into the library.  

The library used to allow this using a `aws.shadow.get_on_connect` per the comment here
https://github.com/mongoose-os-libs/aws/blob/master/include/mgos_aws_shadow.h#L86

I'm guess it got refactored out when migrating to the generic shadow library structure.  This flag also seem to not be used anymore either though
https://github.com/mongoose-os-libs/shadow/blob/master/include/mgos_shadow.h#L70

**Comment by rojer** [comment]
makes sense, easy enough. doing now.

**Comment by rojer** [comment]
ok, i think this is done.
please reopen if it doesn't do the trick.
