### ISSUE TITLE
Unable to clear "desired" state

### ISSUE THREAD

**Issue by arcturial** [mongoose-os-libs/aws#5]
The code comments in your mjs file seem to indicate that you can pass ```{ reported: ... , desired: ... }``` keys to the update function. However, it seems a recent changed removed this and you can only specify ```reported``` fields now.

My question is, how would I clear the desired state? For example, if someone adds a field into the desired state the the application can't actually update, it will continuously try this update everytime it pushes it's own update as a new delta will be triggered. What is the best way to handle this situation?

**Comment by cpq** [comment]
That's by design.
Microsoft's device twin API disallows changing desired , and that is an enforcement of a good practice.
If your device changes desired, you're doing something wrong.

**Comment by arcturial** [comment]
What if desired contains something you can't change?

For example:

```
{
  "desired: {
    "temp": 30
  },
  "reported": {
    "temp": 26 // <- dynamic value read from a sensor
  } 
}
```

It doesn't matter if the user desired a higher temp, the device only reads the environment and publishes it. This will result in an endless amount of delta topics being triggered, since every time the device reads the temp again and publishes...it will differ from the desired and be seen as a delta.

How would you suggest a person addresses this scenario? I am pretty new to shadow states, still trying to figure out best practice.

**Comment by cpq** [comment]
the whole thing does not look correct.
`desired` attributes means that the device could control it - change somehow.
in your case, `temp` is a metric, sensor data that device can't change. That is a wrong usage of shadow.

If `temp` is something like a device can change, e.g. oven temperature, then the whole thing makes sense: user sets `desired`, device reacts, reports, and delta disappears if successful. If not, you can see delta and that's good: you can see that a device fails to do what it supposed to do.

**Comment by matwerber1** [comment]
Hi @cpq. 

I'm running in to the same question / challenge. 

Suppose I have a device that I want to toggle on and off remotely, e.g. via mobile app. Like you say, from the mobile app, I would set `desired` as needed, the delta would push to the device, the device would toggle its state, and the new `reported` state would be reported back. At this point, the delta has been cleared. 

The above makes sense. 

However, what if I want to give the user the option to both control the device remotely **and** in-person? e.g. when home, the user can press a physical button to toggle state. As others have said, in this scenario, as soon as reported state changes at the device when a physical button is pressed, the device reports its new state, a delta is triggered, and the device reverts back to the old state.

**Comment by cpq** [comment]
@matwerber1 that sounds like a valid use case.
Well, there is a workaround : you can send an MQTT packet manually to the shadow update topic.
